--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/yachimm_thomasegh/.config/wpg/wallpapers/fog_branches_trees.jpg"

-- Special
background="#0e0f10"
foreground="#f8feff"
cursor="#f8feff"

-- Colors
color0="#0e0f10"
color1="#374753"
color2="#827CA7"
color3="#75889C"
color4="#4C5D6D"
color5="#9EACC0"
color6="#63748A"
color7="#e4e9ef"
color8="#202325"
color9="#3e5d74"
color10="#9b8eeb"
color11="#86b0dc"
color12="#567999"
color13="#b6dbff"
color14="#7194c2"
color15="#f8feff"
